name: Release

on:
  release:
    types: [created]


jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          sudo apt install protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1

      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.16
          project_path: "./cmd/"
          pre_command: |
            sudo apt install protobuf-compiler
            go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
            make compileProtobuf
          extra_files: README.md LICENSE
          md5sum: FALSE
          sha256sum: TRUE
